### ISSUE TITLE
Problems with rabbitmq

### ISSUE THREAD

**Issue by RibeiroFla** [teogramm/koha-docker#3]
Hello

Koha is running, but for example, when trying to import marc records, the jobs are never processed which means there is a problem with the broker, the logs confirm there is a problem with rabbitmq. I just made 2 small changes, updated S6_OVERLAY_VERSION  and the path to background_jobs_worker.pl

```
Cannot connect to the message broker, the jobs will be processed anyway (Failed to connect: Error connecting to rabbitmq:61613: Connection refused at /usr/share/perl5/Net/Stomp.pm line 27.; giving up at /usr/share/perl5/Net/Stomp.pm line 27.
koha-1       | ) at /usr/share/koha/bin/workers/background_jobs_worker.pl line 92.
koha-1       | DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('database=koha_teolib;host=db;port=3306','koha_teolib',...) failed: Can't connect to MySQL server on 'db' (115) at /usr/share/koha/lib/Koha/Database.pm line 91. at /usr/share/koha/lib/Koha/Database.pm line 139
```

Any solutions or hints are appreciated.

**Comment by teogramm** [comment]
Hi, I haven't worked with Koha in a long time, but I quickly updated everything to its latest version. I ran the ```docker-compose.yaml``` in the examples folder and it seems to work.

As for your problem, you seem to not have enabled the stomp plugin for rabbitmq . You should create a file containing:
```
[rabbitmq_stomp].
```
and mount it as ```/etc/rabbitmq/enabled_plugins``` in the rabbitmq container.

Hope it helps!

**Comment by RibeiroFla** [comment]
Thanks for replying.

Still I didn't manage to get it solved, I'm following the compose file strictly.

veryfing with
```
 docker exec -it examples-rabbitmq-1 bash
cat  /etc/rabbitmq/enabled_plugins
```

[rabbitmq_stomp]. is there, I'm still facing the same issues

```
Cannot connect to the message broker, the jobs will be processed anyway (Failed to connect: Error connecting to rabbitmq:61613: Connection refused at /usr/share/perl5/Net/Stomp.pm line 27.; giving up at /usr/share/perl5/Net/Stomp.pm line 27.
koha-1       | ) at /usr/share/koha/bin/workers/background_jobs_worker.pl line 92.
koha-1       | DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('database=koha_teolib;host=db;port=3306','koha_teolib',...) failed: Can't connect to MySQL server on 'db' (115) at /usr/share/koha/lib/Koha/Database.pm line 91. at /usr/share/koha/lib/Koha/Database.pm line 139
```

**Comment by RibeiroFla** [comment]
Thanks for replying, buddy.

When trying to import a marc binary file into koha, this happens.
```
rabbitmq-1   | 2025-02-08 00:58:32.390313+00:00 [info] <0.605.0> accepting STOMP connection <0.605.0> (172.19.0.2:45672 -> 172.19.0.4:61613)
rabbitmq-1   | 2025-02-08 00:58:32.400674+00:00 [info] <0.605.0> closing STOMP connection <0.605.0> (172.19.0.2:45672 -> 172.19.0.4:61613)
```

**Comment by RibeiroFla** [comment]
The issues with the STOMP plugin have been resolved, but no MARC records can be imported—they remain at '0% Not started' indefinitely. Is that expected? I just want to confirm if you are experiencing the same issue.

```
rabbitmq-1  | 2025-02-09 13:42:22.088782+00:00 [info] <0.579.0> Server startup complete; 1 plugins started.
rabbitmq-1  | 2025-02-09 13:42:22.088782+00:00 [info] <0.579.0>  * rabbitmq_stomp
rabbitmq-1  | 2025-02-09 13:42:22.184295+00:00 [info] <0.10.0> Time to start RabbitMQ: 11526 ms
rabbitmq-1  | 2025-02-09 13:49:03.169817+00:00 [info] <0.667.0> accepting STOMP connection <0.667.0> (172.19.0.5:34378 -> 172.19.0.2:61613)
rabbitmq-1  | 2025-02-09 13:49:03.216350+00:00 [warning] <0.667.0> AMQP 0-9-1 client call timeout was 70000 ms, is updated to a safe effective value of 130000 ms
rabbitmq-1  | 2025-02-09 13:54:10.959904+00:00 [notice] <0.84.0>     alarm_handler: {set,{system_memory_high_watermark,[]}}
rabbitmq-1  | 2025-02-09 13:58:16.060640+00:00 [info] <0.720.0> accepting STOMP connection <0.720.0> (172.19.0.5:55512 -> 172.19.0.2:61613)
rabbitmq-1  | 2025-02-09 13:58:16.176472+00:00 [info] <0.720.0> closing STOMP connection <0.720.0> (172.19.0.5:55512 -> 172.19.0.2:61613)
rabbitmq-1  | 2025-02-09 13:59:55.904633+00:00 [info] <0.757.0> accepting STOMP connection <0.757.0> (172.19.0.5:48564 -> 172.19.0.2:61613)
rabbitmq-1  | 2025-02-09 13:59:55.916544+00:00 [info] <0.757.0> closing STOMP connection <0.757.0> (172.19.0.5:48564 -> 172.19.0.2:61613)
rabbitmq-1  | 2025-02-09 14:01:11.030033+00:00 [notice] <0.84.0>     alarm_handler: {clear,system_memory_high_watermark}
rabbitmq-1  | 2025-02-09 14:04:13.213652+00:00 [info] <0.792.0> accepting STOMP connection <0.792.0> (172.19.0.5:44774 -> 172.19.0.2:61613)
rabbitmq-1  | 2025-02-09 14:04:13.225179+00:00 [info] <0.792.0> closing STOMP connection <0.792.0> (172.19.0.5:44774 -> 172.19.0.2:61613)
```

**Comment by teogramm** [comment]
Yes, I am having the same problem. I did some troubleshooting and it seems that the worker is not getting the jobs from the rabbitmq server. I can't figure out why at the moment.

**Comment by teogramm** [comment]
Got it! The tasks were added to a separate queue, for which there was no worker. I have added another worker service and it now works. Fixed by 7e598d94bd7f9225927adf8bd0a1dcd0e02d302d

**Comment by RibeiroFla** [comment]
I'm still facing the same problem, but anyway, thank you, Teo, for taking the time to help me out. I'll try to figure it out on my own.

**Comment by RibeiroFla** [comment]
Thanks Teo, it worked beautifully.
